[package]
name = "vmal"
version = "1.0.4"
authors = ["Connor Love <connor@dotconnor.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.1"
structopt = "0.3.20"